version: "3"

services:

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    restart: always

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
      args:
        REPO_URL: https://github.com/vikadmin88/client-app.git
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - backend